// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCBVE5QsZ7IAN5GlElnpJazFenBJPcp6-w',
//     appId: '1:691159300275:android:3f04957bd473cdb56d58c6',
//     messagingSenderId: '691159300275',
//     projectId: 'elite-protocol-467015-c0',
//     storageBucket: 'elite-protocol-467015-c0.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAiYIdkUkPLYqMeBUvuNGiYKJ6VepIxOCo',
//     appId: '1:691159300275:ios:3553df90194d521b6d58c6',
//     messagingSenderId: '691159300275',
//     projectId: 'elite-protocol-467015-c0',
//     storageBucket: 'elite-protocol-467015-c0.firebasestorage.app',
//     androidClientId: '691159300275-1urjml7fs3lvsks1rpocbhmrtuf40c9u.apps.googleusercontent.com',
//     iosClientId: '691159300275-s9v0k9mqlbjouq7lhakik86hj99n5gob.apps.googleusercontent.com',
//     iosBundleId: 'com.example.helloTruckDriver',
//   );

// }